RegSet implementation
nalmt/regalloc.rs pull request #1
Opened 2020-03-24 16:25 UTC by nalmt

2020-03-24 16:27 UTC, nalmt commented on lib/src/data_structures.rs
> +type Block = u32;
À supprimer

2020-03-24 16:35 UTC, nalmt commented on lib/src/data_structures.rs
> +type Block = u32;
À supprimer.

2020-04-08 14:00 UTC, moy requested changes

2020-04-08 14:00 UTC, moy commented on lib/src/data_structures.rs
> +        for _ in 0..(other.data.len() - self.data.len()) {
Maybe more natural as

```suggestion
        for _ in self.data.len()..other.data.len() {
```

2020-04-08 14:00 UTC, moy commented on lib/src/data_structures.rs
> +      subset = subset && ((self.data[i] | other.data[i]) == other.data[i]);
You may optimize this with an early return when subset becomes false.

2020-04-08 14:00 UTC, moy commented on lib/src/data_structures.rs
> +      subset = subset && second.data[i] == 0;
Sounds incorrect to me if `self` is shorter than `other`. In this case, there's nothing to check, the extra part of `other` can't result in a false value.

2020-04-15 14:57 UTC, moy commented on lib/src/data_structures.rs
> +      subset = subset && second.data[i] == 0;
Tip: avoid leaving messages like this unanswered, and make it easy for the reviewer to follow, e.g. by answering "Fixed in #2", I've changed it to ...

(GitHub also has a "resolve conversation" button to keep track of what needs to be answered, and what's not).

2020-04-22 13:24 UTC, nalmt commented on lib/src/data_structures.rs
> +      subset = subset && second.data[i] == 0;
Indeed the returned value is wrong if self is shorter than other, here I added a test case: 
https://github.com/nalmt/regalloc.rs/pull/2/commits/fafcc754e36f7202fa64fed2fe24fe4b4d6bdafe

Fixed here:
https://github.com/nalmt/regalloc.rs/pull/2/commits/1b380873235d38c24707505283a84123087931cc

Thank you!

2020-05-06 22:23 UTC, closed without merging

2020-05-07 09:47 UTC, nalmt commented
closed (new pull request opened: https://github.com/nalmt/regalloc.rs/pull/3)